/* 
 * webapi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DateOnly
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DateOnlyTests
    {
        // TODO uncomment below to declare an instance variable for DateOnly
        //private DateOnly instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DateOnly
            //instance = new DateOnly();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DateOnly
        /// </summary>
        [Test]
        public void DateOnlyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DateOnly
            //Assert.IsInstanceOfType<DateOnly> (instance, "variable 'instance' is a DateOnly");
        }


        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Test]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }
        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'DayOfWeek'
        /// </summary>
        [Test]
        public void DayOfWeekTest()
        {
            // TODO unit test for the property 'DayOfWeek'
        }
        /// <summary>
        /// Test the property 'DayOfYear'
        /// </summary>
        [Test]
        public void DayOfYearTest()
        {
            // TODO unit test for the property 'DayOfYear'
        }
        /// <summary>
        /// Test the property 'DayNumber'
        /// </summary>
        [Test]
        public void DayNumberTest()
        {
            // TODO unit test for the property 'DayNumber'
        }

    }

}
