/* 
 * webapi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DayOfWeek
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DayOfWeekTests
    {
        // TODO uncomment below to declare an instance variable for DayOfWeek
        //private DayOfWeek instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DayOfWeek
            //instance = new DayOfWeek();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DayOfWeek
        /// </summary>
        [Test]
        public void DayOfWeekInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DayOfWeek
            //Assert.IsInstanceOfType<DayOfWeek> (instance, "variable 'instance' is a DayOfWeek");
        }



    }

}
