/* 
 * webapi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WeatherForecast
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WeatherForecastTests
    {
        // TODO uncomment below to declare an instance variable for WeatherForecast
        //private WeatherForecast instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WeatherForecast
            //instance = new WeatherForecast();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WeatherForecast
        /// </summary>
        [Test]
        public void WeatherForecastInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WeatherForecast
            //Assert.IsInstanceOfType<WeatherForecast> (instance, "variable 'instance' is a WeatherForecast");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'TemperatureC'
        /// </summary>
        [Test]
        public void TemperatureCTest()
        {
            // TODO unit test for the property 'TemperatureC'
        }
        /// <summary>
        /// Test the property 'TemperatureF'
        /// </summary>
        [Test]
        public void TemperatureFTest()
        {
            // TODO unit test for the property 'TemperatureF'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

    }

}
