/* 
 * webapi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WeatherQueryModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WeatherQueryModelTests
    {
        // TODO uncomment below to declare an instance variable for WeatherQueryModel
        //private WeatherQueryModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WeatherQueryModel
            //instance = new WeatherQueryModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WeatherQueryModel
        /// </summary>
        [Test]
        public void WeatherQueryModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WeatherQueryModel
            //Assert.IsInstanceOfType<WeatherQueryModel> (instance, "variable 'instance' is a WeatherQueryModel");
        }


        /// <summary>
        /// Test the property 'CountryId'
        /// </summary>
        [Test]
        public void CountryIdTest()
        {
            // TODO unit test for the property 'CountryId'
        }

    }

}
