/* 
 * webapi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WeatherForecastApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WeatherForecastApiTests
    {
        private WeatherForecastApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WeatherForecastApi("https://localhost:7030/");
            
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WeatherForecastApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WeatherForecastApi
            //Assert.IsInstanceOfType(typeof(WeatherForecastApi), instance, "instance is a WeatherForecastApi");
        }

        /// <summary>
        /// Test GetWeatherForecast
        /// </summary>
        [Test]
        public void GetWeatherForecastTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            var response = instance.GetWeatherForecast();
            //Assert.IsInstanceOf<List<WeatherForecast>> (response, "response is List<WeatherForecast>");
        }
        /// <summary>
        /// Test WeatherForecastPost
        /// </summary>
        [Test]
        public void WeatherForecastPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WeatherQueryModel body = null;
            //var response = instance.WeatherForecastPost(body);
            //Assert.IsInstanceOf<WeatherQueryModel> (response, "response is WeatherQueryModel");
        }
    }

}
